FROM python:3.7-alpine
ENV PYTHONUNBUFFERED=1

COPY ./requirements.txt /requirements.txt

RUN apk add --update --no-cache jpeg-dev
RUN apk add --update --no-cache --virtual .temp-build-deps \
            gcc libc-dev musl-dev zlib zlib-dev

RUN pip install -r requirements.txt

WORKDIR /app

COPY . /app

#RUN mkdir -p /vol/web/media
#RUN mkdir -p /vol/web/static

#RUN adduser -D user
#RUN chwon -R user:user /vol/
#RUN chmod -R 755 /vol/web
#USER user


