# Generated by Django 3.0.3 on 2020-12-05 19:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('TC', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='TC number must have 11 digits, should not start with Zero', regex='^[1-9]\\d{10}$')])),
                ('gsm', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+90 5xx xxx xxxx'. Up to 15 digits allowed.", regex='^\\+?9?\\d{9,15}$')])),
            ],
        ),
    ]
