# Generated by Django 3.0.3 on 2020-12-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201206_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='no-photo', upload_to='photos/%y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=25, max_digits=6),
            preserve_default=False,
        ),
    ]
